### ISSUE TITLE
[Bug]: Framerate dropping when everytime loading the game, or join/re-join the lobby (!!! Might won't provide modpack code bc this is a confirmed issue !!!)

### ISSUE THREAD

**Issue by CoolLKKPS** [Rune580/LethalCompanyInputUtils#56]
### Acknowledgements

- [X] I use r2modman/thunderstore and will provide a modpack code or zip
- [X] I understand that InputUtils only officially supports the latest version of Lethal Company

### Lobby Related

Yes

### Lobby Acknowledgements

- [X] I understand that all players must have the exact same mod list and have made sure that all players have the exact same modlist.

### InputUtils Version

v0.7.7

### Game Version

v66

### Describe the bug

Framerate dropping when everytime loading the game, or join/re-join the lobby (!!! Might won't provide modpack code bc this is a confirmed issue !!!)

### Reproduction steps

0. using Windows 11 pro 24H2
1. load a save
2. quit to main menu
3. repeat step 1 and 2 multiple times until u think is enough
4. load a save
5. move ur mouse and check the framerate (make sure limit ur CPU cores to only use 1, for windows, open taskmgr)

### ModPack code or file

maybe later

### Logs

[LogOutput.log](https://github.com/user-attachments/files/17558865/LogOutput.log)

**Comment by Rune580** [comment]
> (!!! Might won't provide modpack code bc this is a confirmed issue !!!)
Confirmed by who exactly? I've never confirmed any performance problems caused by InputUtils. (Mostly because it doesn't do anything that would cause a performance hit during gameplay.)

If you're talking about low framerate during the first few seconds after loading a save, that's not caused by InputUtils....
But I doubt you'd believe my word, so let me give you proof.

I launched the game using the Unity Editor Profiler with only InputUtils installed, and profiled loading a game after following your steps (Excluding using Windows, since I'm on Linux). The only thing that runs from InputUtils during this loading is from hooking into `QuickMenuManager.Start()` [to instantiate a prefab that I use for showing tooltips in keybind remap ui](https://github.com/Rune580/LethalCompanyInputUtils/blob/f1d36c6d6b2479a0c3b151ac8b0ab3b5aad3531a/LethalCompanyInputUtils/Patches/QuickMenuManagerPatches.cs#L15)

Looking at the callstack, we can see that the key contributors (specifically added from my hook) add up to 0.6ms.
![image](https://github.com/user-attachments/assets/2ab5aacd-4f97-4268-8206-aae019c1970b)

And if we look at the total percentage, we can see that this only contributes to 0.3% of the total usage of that frame.
![image](https://github.com/user-attachments/assets/61652baf-c6a5-4d3f-ac7e-ab1e2d9ad328)

For reference here's an overview of many of the other contributors to the frame rate. With the InputUtils contributor boxed in red.
![Screenshot_20241029_130841](https://github.com/user-attachments/assets/0459b9a7-a148-41ef-9920-a353d70f3ffe)

I **highly** doubt InputUtils is the source of your "confirmed issue" and it is likely being caused by a combination of mods (which may or may not include InputUtils). But I can promise you it's not InputUtils on it own.

I'll re-open this issue if you provide me with a Modpack.

**Comment by Rune580** [comment]
Here's the modpack code I used for doing these tests: `0192d94b-ba9a-ce67-6b81-c9108684f4a1`

**Comment by CoolLKKPS** [comment]
im not sure why u cannot reproduce this issue, and i didn't connect my controller (maybe? i believe i didn't), but on my test modpack, this could drop the framerate about ~10 FPS, means if u made a larger modpack, the framerate can be terrible

**Comment by CoolLKKPS** [comment]
my modpack link https://1drv.ms/f/c/c26722dc35962b5c/ElwrljXcImcggMKLCgAAAAABXdwXiAVT3j3zNnyNZw3uXg
im still updating, need uninstall some mods

**Comment by Rune580** [comment]
Just to verify, did you check to see if you could reproduce the issue with an empty modpack (excluding BepInEx).

**Comment by CoolLKKPS** [comment]
i did checked in vanilla, don't have this issue in vanilla
